[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/sample"
  to = "/sample.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/security"
  to = "/security.html"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/docs.html"
  status = 200

[[redirects]]
  from = "/user-plan"
  to = "/.netlify/functions/user-plan"
  status = 200

[[redirects]]
  from = "/subnet-calc"
  to = "/subnet-calc.html"
  status = 200
